DROP DATABASE IF EXISTS PRODUCTMANAGEMENTSYSTEM;

CREATE DATABASE PRODUCTMANAGEMENTSYSTEM;

DROP SCHEMA IF EXISTS module_4;

CREATE SCHEMA IF NOT EXISTS module_4;

DROP TABLE IF EXISTS GOODS;

CREATE TABLE module_4.GOODS (
  ID           SERIAL PRIMARY KEY NOT NULL,
  PRODUCT_NAME CHARACTER VARYING  NOT NULL,
  MANUFACTURER CHARACTER VARYING  NOT NULL,
  PRISE        INTEGER            NOT NULL,
  DESCRIPTION  CHARACTER VARYING  NOT NULL
);

